name: Demonstration CI
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: etape 1 -Initialisation
        run : echo "Initialisation"
      - name: etape 2 - Récupération du code
        run : echo " Récupération du code"
      - name: etape 3 - Build
        run : echo "Build"
      - name: etape 4 - Tests
        run : echo "Tests"
      - name: Etape 5 - Packaging
        run : echo  "Packaging"
      - name: etape 6 - Fin du pipeline
        run : echo "Fin du pipeline"
