name: Demonstration CI
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: etape 1 -Initialisation
        run : echo "Initialisation"
      - run : echo "etape 2 - Récupération du code"
      - run : echo "etape 3 - Build"
      - run : echo "etape 4 - Tests"
      - run : echo "etape 2 - Packaging"
      - run : echo "etape 2 - Fin du pipeline"
